---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  storage:
    size: 20Gi
    storageClass: synology-csi-delete
  superuserSecret:
    name: postgres-superuser
  postgresql:
    parameters:
      timezone: "Europe/London"
    shared_preload_libraries:
      - "vchord.so"
  monitoring:
    enablePodMonitor: true
