---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drawio
  namespace: utilities
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: drawio
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      drawio:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: jgraph/drawio
              tag: 29.2.2
            env:
              LETS_ENCRYPT_ENABLED: "false"
              PUBLIC_DNS: "draw.${SECRET_DOMAIN}"
              DRAWIO_BASE_URL: "https://draw.${SECRET_DOMAIN}"
              DRAWIO_SERVER_URL: "https://draw.${SECRET_DOMAIN}"
              DRAWIO_VIEWER_URL: "https://draw.${SECRET_DOMAIN}/js/viewer.min.js"
              DRAWIO_LIGHTBOX_URL: "https://draw.${SECRET_DOMAIN}/."
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 10
                  periodSeconds: 5
                  timeoutSeconds: 3
                  failureThreshold: 3
    service:
      app:
        controller: drawio
        ports:
          http:
            port: 8080
          https:
            port: 8443
    route:
      app:
        hostnames: ["draw.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: 8080
