---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpoller-external-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 30m
  target:
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      data:
        #UP_UNIFI_DEFAULT_API_KEY: "{{ .UNIFI_API_KEY }}"
        UP_UNIFI_DEFAULT_PASS: "{{ .UNIFI_UNPOLLER_PASSWORD }}"
        UP_UNIFI_DEFAULT_URL: "https://unifi.{{ .HOMELAB_SECRET_DOMAIN }}"
        TIMEZONE: "{{ .TIMEZONE }}"
  dataFrom:
    - extract:
        key: unifi-external-secret
    - extract:
        key: homelab-external-secret
