apiVersion: v1
data:
  password: ENC[AES256_GCM,data:I2XfDEpL0WnFsEcJ8QfqTq7ycO/LLRcey2fssx4SFsrx8Ll1H2mTC25FWBfOF9JxCenWiyZW3/KcEmSjSJhb3uDHr8DLCf37ut+Q4O/ID8s=,iv:bHQ7jpaIuRFKiLp9Dq4m39AZtiRelChKk3adiZ783pk=,tag:NHEjp2qgEwyDl3IwEbSofQ==,type:str]
  username: ENC[AES256_GCM,data:b2rgAwXQhHQ=,iv:er/kp3pxnGC+/asz58zYPLBEm7JaKrL6cVx+qjMOlDw=,tag:RSOKcpT3YU+BMD37jBLP+A==,type:str]
kind: Secret
metadata:
  name: cluster-user-auth
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdGl2R2V4cFQzeEpQeHFG
        MVBRYVVsLys1U0d2aVdSTTRndGl6ZitjbjJFCmxHLzN5QXlXME4xY3ozSFAvQUhi
        bjJoK0ptTm8yOGFuOU0zeFNiejVNUE0KLS0tIGxCNzk3d2c5SCthdGE4bHRkVVZR
        VkVKV3h5NU52SDAreTBGcHpkVE9RRUUKkrGGSM/a9nrCW3agBP200qnBdxu90gpO
        se2X62FEcxCHGD5nivCaIxXWwXa4qfJKRZMNFPJbKSu6mvvs66+0ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T09:16:21Z"
  mac: ENC[AES256_GCM,data:6bnanslbxUN4KgZQz5Hm5AiX+mRKy8GqjqJmvoxZ2O4RSrUuG9xv5UNIfrO4DF3znA1Ql8CDt6UrstyiFgBaUNgH3Ry7m9NBGYj3a248asdY3H5SfD/Y8TnyTq05yUZuNSZ2d8TOshkvxbg2QmGdDqpHnUc5JN1TAh4T86SF6Mk=,iv:LZ5uB3huR6Hjr5RFJsw7FRzCqdvHC9ico0j6OjC6upM=,tag:1Om43rxeucoVikZ74luZhw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
