apiVersion: v1
data:
  password: ENC[AES256_GCM,data:z4tgH9SD7eDvz9o/,iv:kffd2oKMAeWUJIiZlatwVpU51GHKLWkzkcrAVEV6BXI=,tag:XbcXai86lJbZEqGTFHLfRA==,type:str]
  username: ENC[AES256_GCM,data:hjkrWHp/PgY=,iv:l+q5QmuvDrs8NPdw2Sw8rhEkx2sgGQk3yHKWqlOESIg=,tag:ynrV8XHqfBuokQVaRYsfaA==,type:str]
kind: Secret
metadata:
  name: cluster-user-auth
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUmZXR1ZMQUpWUURjNEFO
        SmwvQ3BLOUpqdG1hb1BXcmxZSjJVbGIxZmhFClQveGNuc3VjMzJZSm8yaVA0K1pz
        Um1xSFYxcXZKWTA4VUJqOElzcHB1M3MKLS0tIHljUUFVQUJMeU1YVURoMVVrSFpL
        eGZZSUxYWEF3QktmT2NialpTVHNremcKweEZ5Y+D5RGG1WjQR2UYmZD4MeibqShI
        iQUDpFJPZBsmF56DFJN9kKNFOu+LTHHJMy/Zc/UVjEcC2D/bX3TXZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T16:21:31Z"
  mac: ENC[AES256_GCM,data:l4tTc4h6dGUROcQOlDDUPX8AsNgtGqYqZufH4Jz7Yc4pIzwhkifjBNTOTFChHXvs6GUuvduI82Cj2ST0+CBXFjCBDxrHDug479XguQwaJxGNfMfmDOpfAK6kkdtpPXiSmTeLWCpS9CFfCHsKksXoTqrXmIgyhWQbSWT2a93+9eg=,iv:25vOBSzfCIztC+jwk6mG3DPiy9HUMj7OFCZuAAWMi14=,tag:0kKzP+G2N4D5JxHEWzJanA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
