apiVersion: v1
data:
  password: ENC[AES256_GCM,data:ywuiless1rXXvxd41qH/lfbJaB+fFsGuW3kFgBEaxdTiZjT7TP1E3OCmsAYAvANpyGBFQuoAFLA7Gnq1,iv:kovUoDimgmY6v6DYyyDM9+caB7NHTVKYDkncUM//E38=,tag:tLvo2sgV2KXW/uFae4DLVw==,type:str]
  username: ENC[AES256_GCM,data:WLIGyRk=,iv:msM8PpCITIzvtQt2Jq95RvZz8/JyiDQc364Nib11leA=,tag:vRokb70MEbYw3Zfq39Lnaw==,type:str]
kind: Secret
metadata:
  name: cluster-user-auth
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlllKzhqcVZRYXRoVkIw
        d011MjJKS2kyL0ZnWVNQOU9pNEE4eEZjdjNVCk4zdjhSRS9OZ0JkU3VpOGE0bGpz
        akVxVGlpMlpPakkxa3NVRjdlRTdyL2sKLS0tIHpSQy9YUm1VbWk3Z3h6cUsrM2hX
        OU5KU3JiajArQ0ptVWJGeWh4akZpWFkKA/RnUbPRNcLUiyvWfTHQpEASwtjzUxPO
        QOXBpBbMdNOPzQg+rXgxWXIp75qvsUMgJA3clyk90Lsi02jVtYVB+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T08:54:52Z"
  mac: ENC[AES256_GCM,data:gh1t7LaM3KV1p41A1GKrLjJF3OdHUU1ASvtCgyV0sHD0BfAyYf6Cp3KzohNFFG2/sujqy3jy66ttrRlLXhEFONebZqtLEXvHxCI6StyrF2/gORJ9M8MMcXCW85rBawfNJE3siUm2kyaBHPY8D5yVKjdLGvmJXIX7/ExJKzm8O2U=,iv:x1OIRr6Stm5WrPTS3G/B9ib+TzWpu55PCpklcLFvkfA=,tag:FRuJiYKYylQx3VrBM+aPSA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
