---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vikunja
  namespace: utilities
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: vikunja
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudnative-pg
      namespace: database
    - name: onepassword-connect
      namespace: security
  values:
    controllers:
      vikunja:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret vikunja-external-secret
          configmap.reloader.stakater.com/reload: vikunja-configmap
        initContainers:
          01-check-db-ready:
            image:
              repository: postgres
              tag: 18.6
            envFrom:
              - secretRef:
                  name: vikunja-external-secret
            command: ['sh', '-c',
              'if [ -z "$${INIT_POSTGRES_HOST}" ]; then echo "ERROR: INIT_POSTGRES_HOST is not set"; exit 1; fi;
              until pg_isready -h "$${INIT_POSTGRES_HOST}" -p 5432;
              do echo Waiting for PostgreSQL database at $${INIT_POSTGRES_HOST}; sleep 5; done;']
          02-initdb:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.1
            envFrom:
              - secretRef:
                  name: vikunja-external-secret
        containers:
          app:
            image:
              #repository: vikunja/api
              repository: vikunja/vikunja
              #tag: 0.22.1
              tag: 0.24.6
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: vikunja-external-secret
            env:
              #VIKUNJA_SERVICE_TIMEZONE: "${TIMEZONE}"
              VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.${SECRET_DOMAIN}/"
              VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"
              VIKUNJA_SERVICE_ENABLEUSERDELETION: "false"
              VIKUNJA_LOG_LEVEL: "DEBUG"
          #frontend:
          #  image:
          #    repository: vikunja/frontend
          #    #tag: 0.22.1
          #    tag: 0.23.0
          #proxy:
          #  image:
          #    repository: caddy
          #    tag: 2.10.2-alpine
    service:
      app:
        controller: *app
        ports:
          http:
            #port: &port 8080
            port: &port 3456
    route:
      app:
        hostnames: ["vikunja.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      #caddy-config:
      #  type: configMap
      #  name: vikunja-caddy-config
      #  globalMounts:
      #    - path: /etc/caddy/Caddyfile
      #      subPath: Caddyfile
      vikunja-config:
        type: secret
        name: vikunja-external-config
        globalMounts:
          - path: /etc/vikunja/config.yml
            subPath: config.yaml
      config:
        enabled: true
        storageClass: synology-csi-retain
        accessMode: ReadWriteOnce
        type: persistentVolumeClaim
        size: 10Gi
        retain: true
        globalMounts:
          - path: /app/vikunja/files
