apiVersion: v1
data:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:2WwH1pw3CnDwLxAIcbuwEk2lAQPCD2Z9,iv:eODRBebHJ+WHtNjYqjRayoBzAXTDnpyOAbNPecuG/K0=,tag:KQiMJ/YNFD/5Subzdo6sCw==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:EMlwOoMWZ+vla+79,iv:mYVuHW4iumoTINPwF0JU3/k51ootK9mGZTntLwvCTZU=,tag:oh0v00YAIzTvySup3pmRxA==,type:str]
kind: Secret
metadata:
  name: pgadmin-secret
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SnNNb28zSzVzSm9HUHNw
        cUtUdThad3pPMDFhaXFvckorbDJNQWo0UDFVCjE5L0xxRndvZzlsVnNucFBaSUVj
        NGc0N3p0NUxjT0NZYXRQNDNIcno0QXMKLS0tIEwxakc4RWR1SjVFLzZJbk1OM3VX
        TGY2YVczQThVSGhiWU82L3FZR1o4alUKr8SszHehSeQIvhwCeUYcyful/cF93oD1
        4HOf8C194mxKN4kREw/aNJiKvLvq+2ZW7UbSVwV9SkedHl9Vy7FqaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T13:25:41Z"
  mac: ENC[AES256_GCM,data:Sv1dPCtSoyJ1kl8h5B6eM0qxbvuKlFHCHK+m8G3ZeguAK5V8/2e5ClInpoqG2BkHcrQcHwc25R+kIy2iG0ozNIlwKJbqBNL59/8Sz3fpFCAEolH55nnqoXnhkold/jxtEn1HwsALOP90h2TfR5Rd0DJUf1uopWmdupM2eJoJ0kE=,iv:lQq/xBe/i8dTzDQxbS6X6aargfWzOnUp+k+wbWYoeOA=,tag:e0d2d1EY3zjYlWxKd14y/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
