apiVersion: v1
data:
  password: ENC[AES256_GCM,data:/dP4dlFvVKD3VGlK,iv:eKbi3lrYBA6sSCdkJe5yXeDyy61keOXqs0XS8JmilKM=,tag:KvSxgnn8FN5a1LBMhRyalw==,type:str]
  username: ENC[AES256_GCM,data:9O2T6y9KDoUaGrhI,iv:f4C/3smC77VnUmYxKaW1NLf4AbS1yQTyIWifbPPB1V8=,tag:rtS1X86c9iB5yhGQK7Z5tw==,type:str]
kind: Secret
metadata:
  name: postgres-superuser
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZ1JFVzFLVnRRek5MNUho
        dXdlUUlvQkE5RjZDQzFSelRNNFp1SDhucERJCjBTZGZWaEVUdExKZWJIOXVZMit0
        ZnZBekx3WFhaeEZRL3o3NXpmY0FXcjgKLS0tIGY5ckVZdE0zUTFzUUpOQk1YU3Ns
        SStQQ1BjQlhsYlNaMDNFT0VtcVZNd3cK1dt+q5MQM4jxBrxTzT0IcVr4ggWlRAKg
        uJOoi3Ditlx2YaCuJ8V8CM8/i8wYMBrqsK0u26BKJLKh96rxNVRQrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-29T18:54:23Z"
  mac: ENC[AES256_GCM,data:bNDWA3BHezb5GHVQKL/2xI3fepX3usQCx8BjhK0nM/c9ZC/tFbJbBFfJb2JFYwOxCMu8PNRvKt4Kvts31/iGsP70MblH/yVfuOvbAAJY4zAX96s3jYgXNkzluPx4/54tCJDAZMVm/oh6r6hHPvyO5qvTMamuMwPEomCcf0qFUlc=,iv:j4HF65LbsPKTLZ8uqFhu96l8LrNhmYj+NsUSb7okfe8=,tag:LPX26dRwdW+81i+9Wd46xQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
