apiVersion: v1
data:
  password: ENC[AES256_GCM,data:31zW02NO7Y1DIa8v,iv:78Qwj7H8bW4QJUmEcWn0UKxBLMeHoIkqCUr9uyMUOrQ=,tag:Wi0bHrcr2lmtDLqz6P/Ajw==,type:str]
  username: ENC[AES256_GCM,data:xyBTgeTmIzo=,iv:Z5sA6x6L4GG+Wu5rjJ/NTi2FKxzc9xvsQ+zsneGvChU=,tag:vDWjET2i+0S1jtqnbyUl2g==,type:str]
kind: Secret
metadata:
  name: postgres-superuser
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNFBjQjNtcHdtS2ZvNEFv
        YXFXQTBkdDN3bzZuMHV4YlUrY2VUTGlrZ1JNCmpNTndNWURnOEpMeWZFbDQyeFdj
        c2NiMUxNVXZDeU9IUVJjdU1xck5BdHcKLS0tIHI0c3ltSW9sOGVVV2VWMisvZDQ1
        TG5vS0Z3bFFZTnhLMW1Ga3RLUVJaajQKaGNfLv9aV0yz+bergTikA/6FbT0Ykle9
        wOrMbw8AXnSEbpRvEbAX6YIDd+y20VJ2svFth1D4yxGpa4izCdfQmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T12:45:21Z"
  mac: ENC[AES256_GCM,data:NI/FFs8C+6QgTSs48n9J+2NeSXdgUbluhApWXwY5m9NEcv16p6w1CvGnWmjKUQiMAy6+s+x4psLP9qwTEiz943fezYg8fHcyOM1iB8/qE95g4uns6L+XbRRBdWcaH7qZcMktm7a9+Dnd52QK4d/gg4PvvwRnvbfJRTkUyAu0ASk=,iv:RuXcAxJUmjr/VQW4YSTJT481k7GZNw/DrWJbdo7NQIo=,tag:EH7rHcTMLJxXTNMloBdvCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
