# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
data:
  onepassword-credentials.json: ENC[AES256_GCM,data:AZhtUoClxsufh/T/f9ZpHfIi5dfOni7/tH6aJgAWYYx0FkuDpQbjxBAAe0o/P+B9zrdbGe5VIPBVvYI+Ng6lZjYvhMPhSTF5bs7CTTgTAfdb6vvApW/f7yO36vZE26ZR414PoFf+LVaxb9+4CiWT7p0Sg0YeTk3VK0F3h+31KKcf2x5+C2cRYQRsWBcTJqPgKy7/0Nhhb4pB9FEvi7ndt7wgoGiZx+yPkhmdT5WGZ/WvNmUGMC0OfRq0Qsa1zCLQ5k3n+vMal09wk/cJ96xQYwgBHNuj+QIJ3YKfdLXPQCFVMJjAi2T3mkg5ARoLGR8bibjDogeL4JiyntEU2QUmo22GgD6c6Wk4L5F9373c/VpNsVHHcWX0ZQjhTlPE6XXKcfwjBmniGjAIMfRY6IZcYG8zXcFmHpj0A2hoGYFjZUAXqhtLbfRahVfCPpJFJUMZDXwyp6EsKNQ9TCLitX05lQ7twUHJ6P8VNl6ZfQm1Dlji8wWsy2xrOLTkFioq6vUfeD795dyFx/AaAZSJGBKh+X6JVWDlMrtu5o1BCKFv6RKD3wAERVB/IJYMLMPpCiIudA2TRj0c04Nx9wtvbS2eLPQ1XIQaKo5Uu5HxZLjZml98gXJ5bGcxWF7ICIoEj1bVSRwuEGX5dpBoa8fDrydO5Jrd4IJZ3AoMA/nzc2FiYsFUDeXAH4hRR6QajKG8MO1onVlrcnLAd9SVbDmkDFU2x14gBM8EHPBKhEqcvakEFhE5frxZ6IwKbzE4JTfnI56xvFMDI7VWPm7So91bvBzv8v408n28TNSQQnnGU7iHFU8ewD2EOBQ6EfWf03TVNG1EoJCP0u+hzDAtkX1VoXqjylYuVAqmYKo1DcZSC8ZDH0Ku6qYFalNDd5Oonq5qOkgzJ3xSAaMD0dZoY12Cwdt886Dv5VJEUZoNXTAFqhENFGVZaM3PrnD7lCFTZA5qK8rm22sU4tLiRc4ie5ae4+27d/Dk+JxcGSALKvax09dEMbaddUYD172r3oMQwuXcK3JF8ji3rwe1T0uZAjOp6xKCaJ6vytyQlxi/9ZKdDS92+vpLftX7Yfhxr3nvFK9RmM3gJapv8bzAgAR8d0gDJQCn+Or6zoBCQtvmqPMI7tn02enJJ8clacNEEM1i1o7BKSeKEmFhxhtfe6ePIQGHym9HUdKMoW/49vrzuN7AAiZZR+DK4y2E4CUCmQ1/AbdOQHRgngBD0fnA8ttmd3UqI3wrz74qhUSyzCsiWNVsbnRLkpUCHmh8GrI/ot+/VymZsvXyU94P6na/kg/MCLJpcRXxlf/uGc8M1UZSHgyntZfiSFJBaFbwMLSwflCUfnf1IHdyh6GIS67eqH1qM8s4BCGV0xHY3Q7CLPEcXggTvDHa5x5zTPTZA74ka7+GifLyHnbfI54ufC61ukkbWvcu7GOqKql8Wm2Oy4INbBvmKds0rrJAukUMS4ZMtGH7LSXnawRLlWrT+2D7xpB5NcFhg+aZeWbaxwer9YGybmBwucgAQhtxRmWFvp8O6D2PXzdCaG0NML2TKBwnlrL3K7WZSfLaBoXsGixMsVvGW0FGVLUmda46IO3zRYlu7I7tUM8qCUdG27VkH6q9EelG+7qeINwwXa97D74fBxqZMhKb8X6kobxqdpkPdXojiXW9eaGvgJU7uoWAFmHd2JEBsS+KpM3YF6jPlueqQLe+q4941OtVndyn6GI2bIfgBDwHykpwVL47CCMpN29GQ1QUgTTncKRWPi/OjFk5BbIR4SU8X6AuHlpBDE53bUl+cKV+us8tdkvBNw04JjvN8iaP5VMBn3WX26mGsegXMucNroHpRUR9H51eH0dt73wszut9NclGAtaCMLpRkjiUKRvTmevOgBckk+/b671Clv/SkF3na3jen+T4Qe9RaXFbKzpsEvBbPbnSrz7x5I1eiB8gpNM41k/5y0vpUPr0Pscn4EUtWKTXQvwpwjq+2rahsLxbo+Xn/JmkVtSiDxeBAwGFfum5H9bM84Bkn1Zcbkbhy7ya/8h1ge4UBt79wCP4D4B9FIBAQuxKy6V2saNZMZGvWQLm1K2HVmELjsiFL6VMOKcQy3C3q/GqD2QC7mBAuDx4NBfg16RC/TwcuMzfjAWCq9z6axXNlRftJ3aX46fpz7iFQ5US/UpMWx17Fw8oZY2aHaoWP+NW9K0BO8KhKBAs+ZZ0bAqzNPkhH5xuIQY6O2U61xVJeuPI7b7pUhOjyc880aHYlRWFuAYUOczLeYQtIG82r7H7IbA12GHWUWrFz52h/A1iY2NbtZ+VYIemGmHS80V6/7nKpSgivSwkSaZjLjN9dW02nNFL0FX4M5smRIcsChFJ+u//aSc0Z6pK/ncYaRG6DsNjbyAWaMfn2eJt6DmhCm5ebXmFQ1cWPg7tTI7dC3Fv170/nJ/ov4BN4zEEPgydnPwoHENgGFG5Y28MOhwWT4DOB3/D0b6stoXl3ugRCfJO98EX8SrvxIhi7S2iRsG/1icIlXV21NRi1gCxUxTHcoIeUjar2ua1clxEN7h2nE57Q7PeR6aIzt+S7PpcSHYow4iCSqHT4v8zytOGozji1ncSvA==,iv:jh6nCt/axKmNdNniQh7RauZQzcXtyk8v8mFB7ItNxmA=,tag:gN9GAhoceNUVqbadBCS67Q==,type:str]
kind: Secret
metadata:
  name: onepassword-connect-credentials
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUXJHWlBTdkdKNDNnMFor
        K1JsZ1pCcE5ueGcxbmN0TElYY242dW5LVldJCm85YjFNVzM0ZmtnMjZ2czBuL3c5
        b0lxSDRaMVdxRHd5QXpNT3laVnpCSXMKLS0tIGNQdnlHNmtpYUY4d0N5dW5ScWdp
        bFM1UWM4QU4zZk5GTHYrWEtkbEppNlEKb7ZS9cxFq/J1fGOJGaEzXde0igy9WUtY
        xgDAUUBLESqmhjA6hUfrPei4C4cxzaXOT2V1W52R6oOpgE+oGbaCjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T21:16:08Z"
  mac: ENC[AES256_GCM,data:jwBxpkR1zK2reGazngX4ZGu6BPBfuMatZMR1wt05IPC9jWS4DnNpzo8M/RUu1OROPaY17hGrSeK+syhpSrMRsv7AJ7bi74r2fN6/OarGLb28XE+oxiLYyj9BAEcmVoWMSdDV3xJOfj1sMo9TsniZKtZtCarqJ6x/+KX2ZizbPLY=,iv:G4ikRU3+UAkSjS1WRaDXseh15Gtdr8xoVPQSgcJmb2g=,tag:2JsUrYhosx7bX3EKUJS2fA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
data:
  token: ENC[AES256_GCM,data:Sopf6ocJXTN7cm7zmQ6l61n0JalcZgq7nkzsJ2Z4qNWXkwGmODXuVYoU/9efNU5fzspRHIosT8u1WuOeHTsK3X6rJY4h0lhqN7VbdjJyZuVjU3EpTS3/VD2q87OE7JflXPB+rxeo/uv3DR5nhIWgzUXbkq54vYuW0swH7SURRR+OrK/s35/uzIvm4v9WQ/fIqNJNWO0PaggRfI9AnMF1Hk/HL+YLzQ05R7XeLtQhXAf0BxVgWmLRQp6tzYdq92nAdROJY8n9eaiRcPPHxdU1sjV3jde+oxc2GAO0+UXZ64xJZdBYTqJoIQfx2iAKFhiahhANhTyUVGcTiWv7l+lgJnyl7KMD2GsufO9NUyAbBLDNAhxxPX0YEE0Z2tizKAHnz+xJ/EzIwpR8KLu6keFr1xwIj69kn76mtM8ITqrqzjvfbihygfNhoX/NIGclzsTsrK1w9Dq7WVULxQ7t2pZzyiqq+6iab++m8YehQ8M/q7tMdQXIkPuq4P1GCzP0e+oaaWk7Ix04KYEghAaO29TGYv1eanjg9KNKlbNQLxwv+q1rXgi+FlIJgcgGEfuf3UT5i0Z5+yvRAjVreS9X4fCJosqJAjC4PUi3dyXhGKDgdJYRUWECS9oYisEtLz1e5aXToHj6Jx2rn/cKCSs1G2/fi+j7pcfTdTPaa4skEDAJHP47DHEzHw8v3uYPCVMzfdVG7BstWA0escBYC3cFbye1YRq2XIXgrf8L6B93E/Fwkk1WgDC9MpcsKrLbQs3kx0KhE3b7hxhCzfubIwESI+qC9eVUqwZugzYAm7s8Cl11Z9iNv+qEVI/oTmQuheIBEcgEEYkoiGTYo5V5CQpFUi8K16mkNjxt2mGdUMBlqoplW+AvT31r6QDscUAkLZ7PEQDA5hkxdKQ6+qsLbWMPnTwbNEp0mOn70Hdgu3Fh+/BJJKKks94EmPZIAhkPC4JXfsFspGxaM2jNobv9yCE9S6P9dyzepwkxwqWZvHCE+0TzLNOlmvP0LTxvNw4fguuO9jygLcmogvVSTPXGZhNykKFPWrXpTKQ0hjUDVquZGMzDsp6mtQY2AjwZNPJlh2ObgN5BjtkTn9GOPUcyN9tKBOe1Hu4PNX/guUEgp9rC8x5PCYsmnX+rwsX5LsB71vvmfg83Hvlbk8q6dgUipXZCMOPNFsDu60GZG23w4pklxJJWgvCr357ANWf+Az9kdrBjL0TjcbA9aFeGMOyFIr5/UoesTt3ivp1DVXRLPxlg+I/98ClmulbxoPH85ckAWhBvoS+UJsC7pb4yUZbgn8C6h6iih+ng4sFEEM34Xcxnz+zNRk7m3cVV9iwlu44gBoIBJQ4Sb33BEjjdCbKXqoAA+Xbc6/ANszqkdY3/4j3Ik8cF/S6wMYm/ur0nPqKXEZ04NhJQHjYIEsD23BeT4TkndOVTIWxe8grliHnLC1WRRC+txdXYaVxa56ifp0qicrP4x1DoVr3rdBgMLCZyyxHJ6XsU1RLC6tZ2tL16505wXHVK/cB0bE0WT4qegp5D8rruPPwSLLgkULGzHf39uIJcYA+YpjsDDxXxORNHrKXuwj/+0GXtgJyKUL5gLcFP6vhGVam67VgJzdH9ZKcKOqGlEz/lvjEEXsGlcDlPQfA7EjbiO0RxPr1Rt43XuCka51BJk8lrZuN1,iv:gssfJwWRFMed+0PESvXIAK3UfwQllMCMC1V6WrbLLTo=,tag:v9e1jajpi84vGQ35oWLKeA==,type:str]
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: security
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MjNpV00zdjduZXB4b1Za
        Yk1XS085Vno0c2VIRnNVVXNrUjgxcVFDSW1BCnRIeXRFWS9SUjV6NXdNM253Rzc1
        ZmFNL29xRDlCaGcrOTNhKzZaYjlaYnMKLS0tIDU2a1RyNDhwSW1RcjE2T0dyU2l6
        ZTJLaVRqR2NTVXpRYzRqMURiczBjeFEKjSSxEkqBaA75beWTqZV7uiOIUUvJRt2s
        ivvK8NlhnUbRv1JxjQrN/WS2FgZtSU/rETBpHewcLtMMjVBznjVZfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T18:28:45Z"
  mac: ENC[AES256_GCM,data:ZDwjJ9Q7a5LNgP0ifs32PhFTanteGdX0Vwy4us3r7bpJbkKsuCD3wxrDE/89jio+W5VVFKGLycdfACnt8zrJNF9e3YVG7LcnxiSevCdMkZkzXdxnJ6WO4YwvHDeUN0csnqbCfYg2R/VH0tGy08ttI8s2seSoGJwgAo8iT0HD1dE=,iv:bjvnORKYzKX6J/6AhVVGKDiuG/iishYFxyVsvzrqioo=,tag:xbHwzxUxQLZh7A0/FMcWrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUXJHWlBTdkdKNDNnMFor
        K1JsZ1pCcE5ueGcxbmN0TElYY242dW5LVldJCm85YjFNVzM0ZmtnMjZ2czBuL3c5
        b0lxSDRaMVdxRHd5QXpNT3laVnpCSXMKLS0tIGNQdnlHNmtpYUY4d0N5dW5ScWdp
        bFM1UWM4QU4zZk5GTHYrWEtkbEppNlEKb7ZS9cxFq/J1fGOJGaEzXde0igy9WUtY
        xgDAUUBLESqmhjA6hUfrPei4C4cxzaXOT2V1W52R6oOpgE+oGbaCjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-27T21:16:08Z"
  mac: ENC[AES256_GCM,data:jwBxpkR1zK2reGazngX4ZGu6BPBfuMatZMR1wt05IPC9jWS4DnNpzo8M/RUu1OROPaY17hGrSeK+syhpSrMRsv7AJ7bi74r2fN6/OarGLb28XE+oxiLYyj9BAEcmVoWMSdDV3xJOfj1sMo9TsniZKtZtCarqJ6x/+KX2ZizbPLY=,iv:G4ikRU3+UAkSjS1WRaDXseh15Gtdr8xoVPQSgcJmb2g=,tag:2JsUrYhosx7bX3EKUJS2fA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
