apiVersion: v1
data:
  client-info.yml: ENC[AES256_GCM,data:7jh3PWZpCjX+KGjs7cUaVxNATYjBnUiK5VxnE/J7zOwIAqU7ZJ5VHKv9pwgALpJVQBsZquqpwAKFMSwtpmRL2Z+uMU881c/bAms6maR+xeZ1aON+rbGH2rCTlaZ5Z2fgingDkdFOae+FGGfJ6QdlZE9Yt9ijYRKr+Z/tNLOl1354bftM,iv:U9b77EMVI5moEefedWiuivAztnPf0CV1VLssSbI02ek=,tag:ATXaO3FID8n1lMFWPKr7NA==,type:str]
kind: Secret
metadata:
  name: synology-csi-client-info
  namespace: synology-csi
sops:
  age:
    - recipient: age12xg36efrledrxuh7722kwr2973tvp0yzhay4cnfhanzwq4m89g6s63r90a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK05iYXlYcm8zWHo5MjdW
        UmkyR2g2cGNRaGg4M2V5b0VyMXU1Q2U2V0FNCmpzYWw1aXAzV1NCcmxyNFdnZWRt
        bzFGWmVtMHhEZzlwS3N6MmttcUFDVFUKLS0tIDBzTE9UbmR4aWNkMHVTSUNiQzhR
        QVBJM2hVbUtMMXJKVU5nS1ZmMTdIRWMKbCmlk/6BxVPHRDtM1PkgmTGtJrqHVcPc
        dSwm/H9qsRvOWqQR61EkpQmACoLjJKh9lDXLAY6VXZJ1OeXHKD7wYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-24T08:48:37Z"
  mac: ENC[AES256_GCM,data:MgE/0idWExVTGoFo5JQI29ju4/c7uUbd7fCtfcqNNrSx4zSc6ksxgyx5aJyFQucMNEWiu9fOtCPRAEQgfQRJSzivqU3yFnYCsJgtp6jyfRqv7NHcSqXGk2PoPVoFVZcrpVjVRAzYqBimXdZvvkbgogNR69KmrmcmW3Jj1rXB7YU=,iv:S0t5fisW/5hj82ALQW7UXO5hnfwIhhC2R2G7VUFko1I=,tag:rf13x3HJ1/2fn9a2dIkVdg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
