---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-external-secret
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pihole-secret
    template:
      data:
        password: '{{ .PIHOLE_PASSWORD }}'
  dataFrom:
    - extract:
        key: pihole-external-secret
